version: '3'
services:
  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mysql-server
  mysql-server:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=SecureTrends
      - MYSQL_HOST=localhost
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql