CREATE TABLE IF NOT EXISTS ARTICLES(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    platform VARCHAR(255) NOT NULL,
    link VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL
)